openapi: 3.0.3
info:
  title: Ingredient API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /ingredients:
    get:
      tags:
        - Ingredients
      summary: Get all ingredients
      description: Returns all ingredients stored in the database
      responses:
        200:
          description: List of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'

components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          example: 1

        name:
          type: string
          example: Tomato

        price:
          type: number
          format: double
          example: 2.5

        category:
          type: string
          enum:
            - VEGETABLE
            - ANIMAL
            - MARINE
            - DAIRY
            - OTHER
          example: VEGETABLE