openapi: 3.0.3

info:
  title: Ingredient API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /ingredients/{id}:
    get:
      tags: [Ingredients]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        200:
          description: Ingredient found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'

        404:
          description: Ingredient not found
          content:
            text/plain:
              schema:
                type: string
                example: Ingredient.id=1 is not found